modification yaml pour intégrer le nginx avec 443 et nettoyage des fichiers inutiles

diff --git a/webapp/nginx/Dockerfile b/webapp/nginx/Dockerfile
--- a/webapp/nginx/Dockerfile
+++ b/webapp/nginx/Dockerfile
@@ -1,8 +1,83 @@
-# Dockerfile for Nginx
-FROM nginx:alpine
+FROM alpine:3.19
+RUN echo "après download image alpine"
+ENV NGINX_VERSION=1.27.0
+ENV PKG_RELEASE=2
+ENV NJS_VERSION=0.8.4
+ENV NJS_RELEASE=2
+ENV KEY_SHA512=e09fa32f0a0eab2b879ccbbc4d0e4fb9751486eedda75e35fac65802cc9faa266425edf83e261137a2f4d16281ce2c1a5f4502930fe75154723da014214f0655
+ENV nginxPackages="nginx=${NGINX_VERSION}-r${PKG_RELEASE} nginx-module-xslt=${NGINX_VERSION}-r${PKG_RELEASE} nginx-module-geoip=${NGINX_VERSION}-r${PKG_RELEASE} nginx-module-image-filter=${NGINX_VERSION}-r${PKG_RELEASE} \
+nginx-module-njs=${NGINX_VERSION}.${NJS_VERSION}-r${NJS_RELEASE}"
 
+RUN set -x
+# create nginx user/group first, to be consistent throughout docker variants
+    RUN addgroup -g 101 -S nginx 
+    RUN adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx
+    RUN apkArch="$(cat /etc/apk/arch)"
+    #RUN nginxPackages=" \
+    #nginx=${NGINX_VERSION}-r${PKG_RELEASE} \
+#	nginx-module-xslt=${NGINX_VERSION}-r${PKG_RELEASE} \
+ #       nginx-module-geoip=${NGINX_VERSION}-r${PKG_RELEASE} \
+  #      nginx-module-image-filter=${NGINX_VERSION}-r${PKG_RELEASE} \
+   #     nginx-module-njs=${NGINX_VERSION}.${NJS_VERSION}-r${NJS_RELEASE} \
+    #"
+# install prerequisites for public key and pkg-oss checks 
+    RUN apk add --no-cache --virtual .checksum-deps openssl
+    RUN echo "apres openssl"
+# arches officially built by upstream
+            #RUN KEY_SHA512="e09fa32f0a0eab2b879ccbbc4d0e4fb9751486eedda75e35fac65802cc9faa266425edf83e261137a2f4d16281ce2c1a5f4502930fe75154723da014214f0655"
+            RUN wget -O /tmp/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub
+            RUN if echo "$KEY_SHA512 */tmp/nginx_signing.rsa.pub" | sha512sum -c -; then \
+                echo "key verification succeeded!"; \
+                mv /tmp/nginx_signing.rsa.pub /etc/apk/keys/; \
+            else \
+                echo "key verification failed!"; \
+                exit 1; \
+            fi
+            RUN apk add -X "https://nginx.org/packages/mainline/alpine/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" --no-cache $nginxPackages \
+# remove checksum deps
+    && apk del --no-network .checksum-deps \
+# if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
+    && if [ -n "$tempDir" ]; then rm -rf "$tempDir"; fi \
+    && if [ -f "/etc/apk/keys/abuild-key.rsa.pub" ]; then rm -f /etc/apk/keys/abuild-key.rsa.pub; fi \
+# Bring in gettext so we can get `envsubst`, then throw
+# the rest away. To do this, we need to install `gettext`
+# then move `envsubst` out of the way so `gettext` can
+# be deleted completely, then move `envsubst` back.
+    && apk add --no-cache --virtual .gettext gettext \
+    && mv /usr/bin/envsubst /tmp/ \
+    \
+    && runDeps="$( \
+        scanelf --needed --nobanner /tmp/envsubst \
+            | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
+            | sort -u \
+            | xargs -r apk info --installed \
+            | sort -u \
+    )" \
+    && apk add --no-cache $runDeps \
+    && apk del --no-network .gettext \
+    && mv /tmp/envsubst /usr/local/bin/ \
+# Bring in tzdata so users could set the timezones through the environment
+# variables
+    && apk add --no-cache tzdata \
+# Bring in curl and ca-certificates to make registering on DNS SD easier
+    && apk add --no-cache curl ca-certificates \
+# forward request and error logs to docker log collector
+    && ln -sf /dev/stdout /var/log/nginx/access.log \
+    && ln -sf /dev/stderr /var/log/nginx/error.log \
+# create a docker-entrypoint.d directory
+    && mkdir /docker-entrypoint.d
+
+COPY docker-entrypoint.sh /
+COPY 10-listen-on-ipv6-by-default.sh /docker-entrypoint.d
+COPY 15-local-resolvers.envsh /docker-entrypoint.d
+COPY 20-envsubst-on-templates.sh /docker-entrypoint.d
+COPY 30-tune-worker-processes.sh /docker-entrypoint.d
 # Copy custom Nginx configuration
-COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
+COPY default.conf /etc/nginx/conf.d/default.conf
+#Copy certs and key
+COPY nginx.crt /etc/ssl/certs/nginx.crt
+COPY private_key_nginx.key /etc/ssl/private/private_key_nginx.key
+
 
 # Remove symbolic links and create log files
 RUN rm /var/log/nginx/access.log /var/log/nginx/error.log && \
@@ -10,7 +85,10 @@ RUN rm /var/log/nginx/access.log /var/log/nginx/error.log && \
     chmod 644 /var/log/nginx/access.log /var/log/nginx/error.log && \
     chown nginx:nginx /var/log/nginx/access.log /var/log/nginx/error.log
 
-EXPOSE 80
+EXPOSE 443
+
+ENTRYPOINT ["/docker-entrypoint.sh"]
+
+STOPSIGNAL SIGQUIT
 
 CMD ["nginx", "-g", "daemon off;"]
-
